#!/bin/bash
export var1="value1"
export var2="value2"
export var3="value3"
echo "var1 = $var1"
echo "var2 = $var2"
echo "var3 = $var3"
export var4=$var1$var2$var3
echo "var4 = $var4"
echo "Replace var4 with empty string: ${var4//value2}"
echo "Replace var4 with NEW_VALUE string: ${var4//value2/NEW_VALUE}"
